# Generated by Django 3.2.9 on 2021-11-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['commented_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='commented_on',
        ),
    ]
