# Generated by Django 3.2.9 on 2021-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
