# Generated by Django 3.2.9 on 2021-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
